CREATE TABLE Story (
	Id INTEGER PRIMARY KEY IDENTITY(1,1),
	Title NVARCHAR(200) NOT NULL,
	CharacterLimit INTEGER NULL,
	TimeLimit VARCHAR(20) NULL,
	SequenceLimit INTEGER NULL,
	CreatedAt DATETIME2 NOT NULL DEFAULT(GETUTCDATE()),
	Type INTEGER NOT NULL
	)

CREATE TABLE Snippet (
	Id INTEGER NOT NULL,
	StoryId INTEGER NOT NULL REFERENCES Story(Id),
	Text NVARCHAR(MAX) NOT NULL,
	CreatedAt DATETIME2 NOT NULL DEFAULT(GETUTCDATE()),
	Username NVARCHAR(200) NOT NULL,
	UserId NVARCHAR(200) NOT NULL,

	CONSTRAINT pk_Snippet PRIMARY KEY (Id, StoryId)
	)
--- SQLITE

CREATE TABLE "Story" (
	"Id" INTEGER AUTO_INCREMENT PRIMARY KEY,
	"Title" VARCHAR(200) NOT NULL,
	"CharacterLimit" INTEGER NULL,
	"TimeLimit" VARCHAR(20) NULL,
	"SequenceLimit" INTEGER NULL,
	"CreatedAt" DATE NOT NULL DEFAULT(CURDATE()),
	"Type" INTEGER NOT NULL
	);

CREATE TABLE Snippet (
	Id INTEGER NOT NULL,
	StoryId INTEGER NOT NULL REFERENCES Story(Id),
	Text TEXT NOT NULL,
	CreatedAt DATETIME NOT NULL DEFAULT(CURDATE()),
	Username NVARCHAR(200) NOT NULL,
	UserId NVARCHAR(200) NOT NULL,

	CONSTRAINT pk_Snippet PRIMARY KEY (Id, StoryId)
	);

